import type { WordEntry } from './types'

export const seedWords: WordEntry[] = [
  {
    id: 'adapt',
    word: 'adapt',
    phonetic: '/əˈdæpt/',
    pos: 'v.',
    cn: '适应；调整',
    definition: 'to change your behavior or ideas so that you can deal with a new situation',
    level: 'core',
    tags: ['daily', 'work'],
    frq: 1800,
  },
  {
    id: 'approach',
    word: 'approach',
    phonetic: '/əˈprəʊtʃ/',
    pos: 'n./v.',
    cn: '方法；接近',
    definition: 'a way of dealing with something or moving closer to someone or something',
    level: 'core',
    tags: ['thinking'],
    frq: 1500,
  },
  {
    id: 'brief',
    word: 'brief',
    phonetic: '/briːf/',
    pos: 'adj.',
    cn: '简短的',
    definition: 'lasting only a short time or using very few words',
    level: 'core',
    tags: ['writing'],
    frq: 2400,
  },
  {
    id: 'capture',
    word: 'capture',
    phonetic: '/ˈkæptʃər/',
    pos: 'v.',
    cn: '捕捉；记录',
    definition: 'to catch something or record something so it can be kept',
    level: 'core',
    tags: ['memory'],
    frq: 2300,
  },
  {
    id: 'clarify',
    word: 'clarify',
    phonetic: '/ˈklærəfaɪ/',
    pos: 'v.',
    cn: '澄清；说明',
    definition: 'to make an idea or statement easier to understand',
    level: 'core',
    tags: ['communication'],
    frq: 2500,
  },
  {
    id: 'commit',
    word: 'commit',
    phonetic: '/kəˈmɪt/',
    pos: 'v.',
    cn: '投入；承诺',
    definition: 'to decide firmly to do something or support something',
    level: 'core',
    tags: ['habit'],
    frq: 1900,
  },
  {
    id: 'context',
    word: 'context',
    phonetic: '/ˈkɒntekst/',
    pos: 'n.',
    cn: '语境；背景',
    definition: 'the situation in which something happens and that helps explain it',
    level: 'core',
    tags: ['reading'],
    frq: 1200,
  },
  {
    id: 'decay',
    word: 'decay',
    phonetic: '/dɪˈkeɪ/',
    pos: 'n./v.',
    cn: '衰减；衰退',
    definition: 'a gradual loss of strength, quality, or usefulness',
    level: 'advanced',
    tags: ['memory'],
    frq: 6400,
  },
  {
    id: 'deliberate',
    word: 'deliberate',
    phonetic: '/dɪˈlɪbərət/',
    pos: 'adj./v.',
    cn: '深思熟虑的；仔细考虑',
    definition: 'done with careful thought or to think carefully before deciding',
    level: 'advanced',
    tags: ['thinking'],
    frq: 2900,
  },
  {
    id: 'drift',
    word: 'drift',
    phonetic: '/drɪft/',
    pos: 'v./n.',
    cn: '漂移；逐渐偏离',
    definition: 'to move slowly or change direction in an uncontrolled way',
    level: 'advanced',
    tags: ['change'],
    frq: 4100,
  },
  {
    id: 'efficient',
    word: 'efficient',
    phonetic: '/ɪˈfɪʃənt/',
    pos: 'adj.',
    cn: '高效的',
    definition: 'working well without wasting time, energy, or money',
    level: 'core',
    tags: ['work'],
    frq: 1400,
  },
  {
    id: 'engage',
    word: 'engage',
    phonetic: '/ɪnˈɡeɪdʒ/',
    pos: 'v.',
    cn: '参与；吸引',
    definition: 'to become involved in something or to keep someone interested',
    level: 'core',
    tags: ['learning'],
    frq: 1700,
  },
  {
    id: 'friction',
    word: 'friction',
    phonetic: '/ˈfrɪkʃən/',
    pos: 'n.',
    cn: '摩擦；阻力',
    definition: 'a force or difficulty that makes movement or progress less smooth',
    level: 'advanced',
    tags: ['productivity'],
    frq: 4800,
  },
  {
    id: 'habit',
    word: 'habit',
    phonetic: '/ˈhæbɪt/',
    pos: 'n.',
    cn: '习惯',
    definition: 'something you do regularly, often without thinking about it',
    level: 'core',
    tags: ['routine'],
    frq: 1300,
  },
  {
    id: 'insight',
    word: 'insight',
    phonetic: '/ˈɪnsaɪt/',
    pos: 'n.',
    cn: '洞察；理解',
    definition: 'a clear and deep understanding of a person or situation',
    level: 'core',
    tags: ['thinking'],
    frq: 2100,
  },
  {
    id: 'interval',
    word: 'interval',
    phonetic: '/ˈɪntəvəl/',
    pos: 'n.',
    cn: '间隔',
    definition: 'a period of time between two events or actions',
    level: 'core',
    tags: ['memory'],
    frq: 3600,
  },
  {
    id: 'maintain',
    word: 'maintain',
    phonetic: '/meɪnˈteɪn/',
    pos: 'v.',
    cn: '维持；保持',
    definition: 'to keep something at the same level or in good condition',
    level: 'core',
    tags: ['habit'],
    frq: 1600,
  },
  {
    id: 'notion',
    word: 'notion',
    phonetic: '/ˈnəʊʃən/',
    pos: 'n.',
    cn: '概念；想法',
    definition: 'an idea or belief about something',
    level: 'core',
    tags: ['thinking'],
    frq: 2600,
  },
  {
    id: 'pace',
    word: 'pace',
    phonetic: '/peɪs/',
    pos: 'n./v.',
    cn: '节奏；踱步',
    definition: 'the speed at which something happens or the act of walking back and forth',
    level: 'core',
    tags: ['routine'],
    frq: 2000,
  },
  {
    id: 'retain',
    word: 'retain',
    phonetic: '/rɪˈteɪn/',
    pos: 'v.',
    cn: '保持；记住',
    definition: 'to keep something or continue to have something',
    level: 'core',
    tags: ['memory'],
    frq: 2700,
  },
  {
    id: 'signal',
    word: 'signal',
    phonetic: '/ˈsɪɡnəl/',
    pos: 'n./v.',
    cn: '信号；表明',
    definition: 'a sign, message, or action that communicates information',
    level: 'core',
    tags: ['communication'],
    frq: 2200,
  },
  {
    id: 'streak',
    word: 'streak',
    phonetic: '/striːk/',
    pos: 'n.',
    cn: '连续的一段时间',
    definition: 'a continuous period of success or regular activity',
    level: 'core',
    tags: ['habit'],
    frq: 5200,
  },
  {
    id: 'sustain',
    word: 'sustain',
    phonetic: '/səˈsteɪn/',
    pos: 'v.',
    cn: '维持；支撑',
    definition: 'to keep something going for a period of time',
    level: 'advanced',
    tags: ['habit'],
    frq: 3200,
  },
  {
    id: 'trigger',
    word: 'trigger',
    phonetic: '/ˈtrɪɡər/',
    pos: 'n./v.',
    cn: '触发因素；引发',
    definition: 'something that causes an event to start or makes it happen',
    level: 'core',
    tags: ['memory'],
    frq: 3100,
  },
]
